module.exports = {
    DECLARATION: 'DECLARATION',
    ASSIGNMENT: 'ASSIGNMENT',
    PROP_ASSIGNMENT: 'PROP_ASSIGNMENT',
    ACCESSOR: 'ACCESSOR',
    EXPRESSION: 'EXPRESSION',
    METHODCALL: 'METHODCALL',
    CALL: 'CALL',
    DELETE: 'DELETE',
    SPREAD: 'SPREAD',
    METHOD: 'METHOD',
    RETURN: 'RETURN',
    BLOCK: 'BLOCK',
    FUNC: 'FUNC',
    PROGRAM: 'PROGRAM',
    GET: 'GET',
    SET: 'SET'
}